### ISSUE TITLE
rsync from a list of files

### ISSUE THREAD

**Issue by bernardohenz** [cboudereau/gcs-rsync#17]
Hi,

I have a huuge dataset and I only want to sync some of the files.
The traditional `rsync` allows for that (using `--files-from`), but the rsync on gsutil does not have this functionality.

Does your implementation allow such a thing? If not, can this be implemented?

**Comment by cboudereau** [comment]
Hi! I am actually on holidays.

It this totally possible to add a filter.

A good start could be to add a function to the builder to add the filter
like the restore fs time and update the sync function by applying the
filter after the list() call.

**Comment by cboudereau** [comment]
While I am implementing the feature, there is might be an example that could fit with your need: if you already now which files you have to sync, you could use this [example](https://github.com/cboudereau/gcs-rsync/blob/main/examples/upload_object.rs)

**Comment by cboudereau** [comment]
Hi @bernardohenz, sorry for the huge delay.

I am implementing the feature in #19.

I have found a reasonable trade-offs by adding --include and --exclude from the CLI which can be filled multiple times.

The library has also been updated. I don't want to add the --files-from before adding include and exclude glob pattern.

**Comment by cboudereau** [comment]
@bernardohenz, the new version is published (v0.3.1) which supports include and exclude glob patterns as described in the pr #19  👍

**Comment by cboudereau** [comment]
I am gonna close the issue.

As I mentioned, we will introduce exclusion from a file later since the exclusion argument can be repeated.
