### ISSUE TITLE
(question) does this client support fetching individual bucket objects? 

### ISSUE THREAD

**Issue by trevorbernard** [cboudereau/gcs-rsync#29]
For example:

```
gsutil cp "gs://mina_network_block_data/mainnet-2-*.json" .
```

**Comment by cboudereau** [comment]
Hi!

This lib and cli uses glob pattern to include or exclude files.

Here is an example used by
- gcs-rsync bin CLI
  - [includes argument](https://github.com/cboudereau/gcs-rsync/blob/main/examples/gcs-rsync.rs#L35) used by the client builder 
  - [excludes argument](https://github.com/cboudereau/gcs-rsync/blob/main/examples/gcs-rsync.rs#L39)
- Library
  - [with_includes](https://github.com/cboudereau/gcs-rsync/blob/main/examples/gcs-rsync.rs#L90) and 
  - [with_excludes](https://github.com/cboudereau/gcs-rsync/blob/main/examples/gcs-rsync.rs#L97)

**Comment by cboudereau** [comment]
I just created a PR to document this feature.

https://github.com/cboudereau/gcs-rsync/tree/doc/glob-pattern?tab=readme-ov-file#include-or-exclude-files-using-glob-pattern

You can also find useful example in the tests folder which are integration tests of the library: https://github.com/cboudereau/gcs-rsync/blob/main/tests/sync_mirror_integration_tests.rs#L428

**Comment by cboudereau** [comment]
I closed the question but feel free to reopen it if needed.

**Comment by trevorbernard** [comment]
@cboudereau Awesome, thanks for the quick response! Is there an option to download w/o providing credentials? I tried an example on a publicly accessible bucket but it came with `Error: GcsTokenError(EnvVarError { key: "GOOGLE_APPLICATION_CREDENTIALS", error: NotPresent })`.

**Comment by cboudereau** [comment]
If you are running inside gcp you can use the Google metadata api for
authentication:
https://github.com/cboudereau/gcs-rsync/blob/main/examples/gcs-rsync.rs#L23

**Comment by cboudereau** [comment]
In that case you can fill the environment var which is the same as gsutil.

You can follow the quick setup from the Auth reader over here:
https://github.com/cboudereau/gcs-rsync/tree/main/src/gcp/oauth2

**Comment by cboudereau** [comment]
I created the PR to add a no_auth feature on both CLI and library to download only public sources.

I'll publish the crate shortly.

Feel free to reopen it later if you think that there is still something missing 👍

**Comment by cboudereau** [comment]
The example is available here: https://github.com/cboudereau/gcs-rsync/blob/main/examples/download_public_object.rs

**Comment by cboudereau** [comment]
The v0.4.0 has been published 👍
